### ISSUE TITLE
Support for the class based GraphQL API

### ISSUE THREAD

**Issue by phyrog** [ontohub/graphql-pundit#30]
The block passed to `field` is now executed in a different context (a proxy object), so the authorization helpers are not available here. The field is still accessible via `@field`, so if we find a way to call the helpers in the proxy object, we can still set the metadata on the fields.

**Comment by gastonmorixe** [comment]
1.8.0 released with heavy class based support. Any roadmap on this?

**Comment by phyrog** [comment]
Thanks for the ping on this!

Plans sure, however I currently can't give an estimate (at least a couple of weeks) on how soon due to a lot of other work at the moment. Using this gem with 1.8 should still be possible with the old style of definitions for now.

**Comment by casiodk** [comment]
I also really need this :)

**Comment by phyrog** [comment]
I'll probably be able to get to it next week, after I have taken another look at the new API to see how instrumenters can be used now (last time I checked this was not implemented yet).

**Comment by casiodk** [comment]
Hey :) How is it coming along. Can I do something to help?

**Comment by phyrog** [comment]
I started playing around with the new API yesterday; as most changes are internally, I still need to check out the interaction between the `.define` based API and the class based one, to see if my planned approach works for both.

Usage-wise, I don't expect much change here:

```ruby
field :foobar, ... do
  authorize :foo, policy: FooPolicy ... # this should still work without changes
end
```

but I'm also thinking about supporting one-line field definitions (which did not work previously, I think):

```ruby
field :foobar, ..., authorize: :foo, policy: FooPolicy
```

It'll definitely take me a couple more days to figure all that out, but I think a PR and new release next week should definitely be realistic.

**Comment by casiodk** [comment]
That sounds awesome, looking forward!

**Comment by haizop** [comment]
Thanks for working on this. I am building a new class based api and I would really like to use this gem.

**Comment by iamjbecker** [comment]
Is there an estimated time on #50 being merged into master?

**Comment by eugenk** [comment]
By the end of the day, I presume :)

**Comment by iamjbecker** [comment]
Awesome! Looking forward to taking this for a spin. Looking forward to contribute a bit in the future as well.

**Comment by phyrog** [comment]
Version `0.7.0` was just released. If there are any problems, don't hesitate to open issues :tada:

**Comment by durcak** [comment]
@phyrog are you planning to add compatibility for new `GraphQL::Execution::Interpreter` and `GraphQL::Execution::Errors` ?

**Comment by phyrog** [comment]
Hey @durcak, thanks for your interest in this project. I haven't worked with this gem (or graphql-ruby) for a while now and would have to dig into the code again (esp. graphql-ruby, I remeber them changing a lot of the internal structure last year).

I can certainly review a PR, if you feel up for it yourself 🙂

**Comment by durcak** [comment]
Hi, I just find easy solution, just add `alias_method :resolve, :resolve_field` to `Graphql::Pundit::Authorization` module, because the interpreter calls a different method: `#resolve(obj, args, ctx)`, instead of `#resolve_field`.  

There are two differences with the new method:
  - `args` is plain ol' Ruby Hash, with symbol keys, instead of a `GraphQL::Query::Arguments`
  - `ctx` is a `GraphQL::Query::Context` instead of a `GraphQL::Query::Context::FieldResolutionContext`

Edit:
- just adding alias is not enought
